name: Run Actions Tests

on:
  pull_request:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: RUn test
        run: |
          pytest NieWiem.py